language: node_js
node_js:
- '0.11'
- '0.10'

before_install:
  # init browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  # install ruby packages
  - gem update --system
  - gem install sass --version "=3.2.12"
  - gem install compass --version "=0.12.2"
  # bower!!
  - npm install -g bower
  - bower install
  - cd test
  - bower install
  - cd ..